# Generated by Django 2.0.6 on 2018-08-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicInfo',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='likedPhotos',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='likedUsers',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blockedUsers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visitors',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
