# Generated by Django 2.0.6 on 2018-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
