# Generated by Django 2.0.6 on 2018-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
