# Generated by Django 2.0.6 on 2018-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_auto_20180812_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(to='matchmaker.Interest'),
        ),
    ]
