# Generated by Django 2.0.6 on 2018-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_auto_20180804_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(to='matchmaker.Interest'),
        ),
    ]
