# Generated by Django 2.0.6 on 2018-08-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_userprofile_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='views',
            new_name='visitors_view_count',
        ),
    ]
