# Generated by Django 2.0.6 on 2018-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_auto_20180813_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='color',
            field=models.CharField(default='teal', max_length=15),
        ),
    ]
