# Generated by Django 2.0.6 on 2018-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitinfo',
            name='diet',
            field=models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Kosher', 'Kosher'), ('I eat meat', 'I eat meat'), ('Halal', 'Halal'), ('Vegetarian', 'Vegetarian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitinfo',
            name='drinking',
            field=models.CharField(blank=True, choices=[('Drinking', '\tDrinking'), ('Sometimes', 'Sometimes'), ('Socially', 'Socially'), ('Never', 'Never'), ('Often', 'Often')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitinfo',
            name='drug',
            field=models.CharField(blank=True, choices=[('Often', 'Often'), ('Never', 'Never'), ('Sometimes', 'Sometimes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitinfo',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Only with alcohol', 'Only with alcohol'), ('Social smoker', 'Social smoker'), ('Trying to quit', 'Trying to quit'), ('Non-smoker', 'Non-smoker'), ('Quit', 'Quit'), ('Smoker', 'Smoker')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='car',
            field=models.BooleanField(choices=[(False, "I don't have one"), (True, 'I have my own car')], default=False),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='children',
            field=models.CharField(blank=True, choices=[('Expecting', 'Expecting'), ('Want kids', 'Want kids'), ('Have kids', 'Have kids'), ("Don't want kids", "Don't want kids"), ('No kids', 'No kids'), ('Someday', 'Someday'), ('Might want kids', 'Might want kids')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='home_ownership',
            field=models.CharField(blank=True, choices=[('Live in a dormitory', 'Live in a dormitory'), ('Own a house/apartments', 'Own a house/apartments'), ('Share a flat', 'Share a flat'), ('Rent a house/apartments', 'Rent a house/apartments'), ('Live with parents', 'Live with parents')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='pets',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Hate pets', 'Hate pets'), ('Dogs', 'Dogs'), ('Cats', 'Cats')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professionalinfo',
            name='education',
            field=models.CharField(blank=True, choices=[('College', 'College'), ("I'm just very smart", "I'm just very smart"), ('Post grad', 'Post grad'), ('Secondary education', 'Secondary education'), ('Not finished', 'Not finished'), ('University', 'University'), ('Apprenticeship', 'Apprenticeship'), ('Advanced degree', 'Advanced degree')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professionalinfo',
            name='industry',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Non-profit', 'Non-profit'), ('Health care', 'Health care'), ('Education', 'Education'), ('Arts/music/writing', 'Arts/music/writing'), ('Technology', 'Technology'), ('Sales/marketing', 'Sales/marketing'), ('Hospitality', 'Hospitality'), ('Entertainment/media', 'Entertainment/media'), ('Business management', 'Business management'), ('Transportation', 'Transportation'), ('IT', 'IT'), ('Military', 'Military'), ('Government/politics', 'Government/politics'), ('Construction', 'Construction')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professionalinfo',
            name='profession',
            field=models.CharField(blank=True, choices=[('College student', 'College student'), ('Homemaker', 'Homemaker'), ('Apprentice', 'Apprentice'), ('Retired', 'Retired'), ('Employee', 'Employee'), ('Self-employed', 'Self-employed'), ('Civil servant', 'Civil servant'), ('Unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('In an open relationship', 'In an open relationship'), ('Single', 'Single'), ('Tell you later', 'Tell you later'), ('Seeing someone', 'Seeing someone'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Monogamous', 'Monogamous'), ('Polygamous', 'Polygamous')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('Straight', 'Straight'), ('Bisexual', 'Bisexual'), ('Gay', 'Gay')], max_length=20, null=True),
        ),
    ]
