# Generated by Django 2.0.6 on 2018-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0007_auto_20180821_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='body_type',
            field=models.CharField(choices=[('A little extra', 'A little extra'), ('Fit', 'Fit'), ('Full-figured', 'Full-figured'), ('Average', 'Average'), ('Better not say', 'Better not say'), ('Curvy', 'Curvy'), ('Overweight', 'Overweight'), ('Thin', 'Thin')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='ethnicity',
            field=models.CharField(choices=[('Black/African descent', 'Black/African descent'), ('Pacific islander', 'Pacific islander'), ('Indian', 'Indian'), ('White/Caucasian', 'White/Caucasian'), ('Mixed', 'Mixed'), ('Middle eastern', 'Middle eastern'), ('Asian', 'Asian'), ('Other', 'Other'), ('Native american', 'Native american'), ('Latino/ hispanic', 'Latino/ hispanic')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Agnostic', 'Agnostic'), ('Spiritual', 'Spiritual'), ('Orthodox', 'Orthodox'), ('Catholic', 'Catholic'), ('Atheist', 'Atheist'), ('Other', 'Other'), ('Jewish', 'Jewish'), ('Protestant', 'Protestant'), ('Christian', 'Christian'), ('Muslim', 'Muslim')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sign',
            field=models.CharField(choices=[('Sagittarius', 'Sagittarius'), ('Virgo', 'Virgo'), ('Gemini', 'Gemini'), ('Pisces', 'Pisces'), ('Capricorn', 'Capricorn'), ('Libra', 'Libra'), ('Cancer', 'Cancer'), ('Aries', 'Aries'), ('Scorpio', 'Scorpio'), ('Leo', 'Leo'), ('Taurus', 'Taurus'), ('Aquarius', 'Aquarius')], default='-', max_length=20),
        ),
    ]
