# Generated by Django 2.0.6 on 2018-08-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0008_auto_20180821_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='home_ownership',
            field=models.CharField(blank=True, choices=[('Live in a dormitory', 'Live in a dormitory'), ('Own a house/apartments', 'Own a house/apartments'), ('Share a flat', 'Share a flat'), ('Rent a house/apartments', 'Rent a house/apartments'), ('Live with parents', 'Live with parents')], default='-', max_length=20),
        ),
    ]
