# Generated by Django 2.1.7 on 2019-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0009_auto_20180821_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='car',
            field=models.BooleanField(blank=True, choices=[(False, "I don't have one"), (True, 'I have my own car')], default=False),
        ),
    ]
