# Generated by Django 2.1.7 on 2019-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0011_auto_20190223_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
