	FILMS_AND_TV_SERIES_CHOCIES = (('Comedy','Comedy'), 
	('Action','Action'), 
	('Adventure','Adventure'), 
	('Drama','Drama'), 
	('Romantic','Romantic'), 
	('comedy','comedy'), 
	('Documentary','Documentary'), 
	('Horror','Horror'), 
	('Science','Science'), 
	('fiction','fiction'), 
	('Fantasy','Fantasy'), 
	('Historical','Historical'), 
	('Animated','Animated'), 
	('films','films'), 
	('Musicals','Musicals'), 
	('Police','Police'), 
	('drama','drama'), 
	('Cartoons','Cartoons'), 
	('Arthouse','Arthouse'), 
	('Thriller','Thriller'), 
	('Discovery','Discovery'), 
	('Anime','Anime'), 
	('Crime','Crime'), 
	('drama','drama'), 
	('Melodrama','Melodrama'), 
	('Reality show','Reality show'),)